# Generated by Django 5.1.6 on 2025-03-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramaardhaapp', '0005_subservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
