# Generated by Django 5.1.6 on 2025-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaardhaapp', '0006_remove_service_price_delete_subservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='service_images/default.jpg', upload_to='service_images/'),
        ),
    ]
