# Generated by Django 5.1.6 on 2025-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaardhaapp', '0009_alter_service_image_subservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subservices/'),
        ),
    ]
